SELECT SUBSTR(TO_CHAR(SALES_DATE, 'YYYY-MM-DD'),0,10) AS SALES_DATE
      ,PRODUCT_ID
      ,USER_ID
      ,SALES_AMOUNT
FROM ONLINE_SALE
WHERE SUBSTR(TO_CHAR(SALES_DATE, 'YYYY-MM-DD'),0,7) = '2022-03'
UNION ALL
SELECT SUBSTR(TO_CHAR(SALES_DATE, 'YYYY-MM-DD'),0,10) AS SALES_DATE
      ,PRODUCT_ID
      ,NULL AS USER_ID
      ,SALES_AMOUNT
FROM OFFLINE_SALE
WHERE SUBSTR(TO_CHAR(SALES_DATE, 'YYYY-MM-DD'),0,7) = '2022-03'
ORDER BY SALES_DATE, PRODUCT_ID, USER_ID