-- 코드를 입력하세요
SELECT YEAR(B.SALES_DATE) AS 'YEAR', 
       MONTH(B.SALES_DATE) AS 'MONTH', 
       A.GENDER, COUNT(DISTINCT(B.USER_ID)) AS 'USERS'
FROM USER_INFO A, ONLINE_SALE B
WHERE A.USER_ID=B.USER_ID
AND !ISNULL(A.GENDER)
GROUP BY YEAR, MONTH, A.GENDER
ORDER BY YEAR, MONTH, A.GENDER;