-- 코드를 작성해주세요
SELECT GR.EMP_NO, EM.EMP_NAME,   
    (CASE
        WHEN AVG(GR.SCORE) >= 96 THEN 'S'
        WHEN AVG(GR.SCORE) >= 90 THEN 'A'
        WHEN AVG(GR.SCORE) >= 80 THEN 'B'
        ELSE 'C'
    END) AS 'GRADE',
    EM.SAL*(CASE
        WHEN AVG(GR.SCORE) >= 96 THEN 0.2
        WHEN AVG(GR.SCORE) >= 90 THEN 0.15
        WHEN AVG(GR.SCORE) >= 80 THEN 0.1
        ELSE 0
    END) AS 'BONUS'
FROM HR_DEPARTMENT DE, HR_EMPLOYEES EM, HR_GRADE GR
WHERE DE.DEPT_ID = EM.DEPT_ID AND EM.EMP_NO = GR.EMP_NO
GROUP BY GR.EMP_NO
ORDER BY GR.EMP_NO;