SELECT ID,FISH_NAME,LENGTH
FROM(
    SELECT ID,FISH_TYPE,LENGTH 
    FROM FISH_INFO
    WHERE (FISH_TYPE, LENGTH) IN (
        SELECT FISH_TYPE,MAX(LENGTH) AS LENGTH
        FROM FISH_INFO
        GROUP BY FISH_TYPE
    )
)A, (SELECT FISH_TYPE, FISH_NAME FROM FISH_NAME_INFO) B
WHERE A.FISH_TYPE = B.FISH_TYPE
ORDER BY ID;